clear all, close all

% folder list
fldList = {'pulvinar_both', 'pulvinar_ambiguous', 'pulvinar_eye', ...
    'LGN_both', 'LGN_ambiguous', 'LGN_eye', ...
    'V4_both', 'V4_ambiguous', 'V4_eye', 'pulvinar_response', ...
    'pulvinar_noResponse', 'pulvinar_both1', 'pulvinar', ...
    'pulvinar_ambiguous_half1_1', 'pulvinar_ambiguous_half2_1', ...
    'pulvinar_ambiguous_half1_2', 'pulvinar_ambiguous_half2_2', ...
    'pulvinar_ambiguous214_half1_1', 'pulvinar_ambiguous214_half2_1', ...
    'pulvinar_ambiguous214_half1_2', 'pulvinar_ambiguous214_half2_2'};

% fldList = {'LGN_alpha_ambiguous', 'V4_alpha_both', 'V4_beta_both', ...
%     'pulvinar_alpha_both', 'pulvinar_beta_both', 'LGN_alpha_both' , ...
%     'LGN_alpha_physical', 'LGN_beta_ambiguous', 'V4_alpha_physical', ...
%     'V4_beta_physical', 'pulvinar_alpha_physical', 'pulvinar_beta_physical', ...
%     'LGN_beta_both', 'LGN_beta_physical', 'V4_alpha_ambiguous', ...
%     'V4_beta_ambiguous', 'pulvinar_alpha_ambiguous', 'pulvinar_beta_ambiguous'};

% {'allAreas_ambiguous', 'allAreas_both', 'allAreas_physical', ...
%     'LGN_ambiguous', 'LGN_both', 'LGN_physical', ...
%     'pulvinar_ambiguous', 'pulvinar_both', 'pulvinar_physical', ...
%     'V4_ambiguous', 'V4_both', 'V4_physical', ...
%     ...
%     'allAreas_ambiguous_le', 'allAreas_both_le', 'allAreas_physical_le', ... % for left eye
%     'LGN_ambiguous_le', 'LGN_both_le', 'LGN_physical_le', ...
%     'pulvinar_ambiguous_le', 'pulvinar_both_le', 'pulvinar_physical_le', ...
%     'V4_ambiguous_le', 'V4_both_le', 'V4_physical_le', ...
%     ...
%     'allAreas_ambiguous_re', 'allAreas_both_re', 'allAreas_physical_re', ... % for right eye
%     'LGN_ambiguous_re', 'LGN_both_re', 'LGN_physical_re', ...
%     'pulvinar_ambiguous_re', 'pulvinar_both_re', 'pulvinar_physical_re', ...
%     'V4_ambiguous_re', 'V4_both_re', 'V4_physical_re'};

% binning parameters
bin_width = 250;
step_size = 50;

% %for BLP
% bin_width = 1;
% step_size = 1;

for fldNum = 18:length(fldList)
    raster_file_directory_name = ['.\' fldList{fldNum}];
    save_prefix_name = ['Binned_data_' fldList{fldNum}];
    
    % create binned data
    create_binned_data_from_raster_data(raster_file_directory_name, save_prefix_name, bin_width, step_size);
end
