% clear all, close all

folderList = ...
    {'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_alpha\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_alpha\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_beta\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_beta\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_gamma1\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_gamma1\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_gamma2\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_gamma2\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_mua\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response0_mua\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_alpha\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_alpha\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_beta\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_beta\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_gamma1\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_gamma1\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_gamma2\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_gamma2\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_mua\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V2_ambiguous_response1_mua\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_alpha\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_alpha\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_beta\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_beta\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_gamma1\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_gamma1\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_gamma2\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_gamma2\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_mua\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response0_mua\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_alpha\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_alpha\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_beta\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_beta\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_gamma1\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_gamma1\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_gamma2\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_gamma2\shuff\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_mua\', ...
    'C:\Users\lvasileva\Documents\Luba\scripts\ndt_prep\GFS_Tuebingen\results_V4_ambiguous_response1_mua\shuff\', ...
    };

for folderNum = 1:length(folderList)
    gfs_rename_files_(folderList{folderNum})
end

function gfs_rename_files_(folderName)

cd(folderName)

fileList = dir([folderName filesep '*.mat']);

for fileNum = 1:length(fileList)
    
%     % Add 'Results' to the beginning of the file name
%     oldName = fileList(fileNum).name;
%     newName = ['Results' fileList(fileNum).name];
    
    % Replace Binned_data with Results in the file name
    oldName = fileList(fileNum).name;
    newName = ['Results' fileList(fileNum).name(12:end)];
    
    movefile(oldName, newName)
    
end
end

