clear all, close all

flList = {...
%     'Binned_data_LGN_matchUnits_ambiguous_alpha_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_ambiguous_beta_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_ambiguous_delta_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_ambiguous_theta_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_ambiguous_gamma1_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_ambiguous_gamma2_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_ambiguous_spk_250ms_bins_50ms_sampled', ...
%     ...
%     'Binned_data_LGN_matchUnits_both_alpha_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_both_beta_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_both_delta_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_both_gamma1_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_both_gamma2_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_both_spk_250ms_bins_50ms_sampled', ...
%     'Binned_data_LGN_matchUnits_both_theta_250ms_bins_50ms_sampled', ...
    ...
%     'Binned_data_V4_matchUnits_ambiguous_alpha_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_ambiguous_beta_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_ambiguous_delta_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_ambiguous_gamma1_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_ambiguous_gamma2_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_ambiguous_spk_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_ambiguous_theta_250ms_bins_50ms_sampled', ...
%     ...
%     'Binned_data_V4_matchUnits_both_alpha_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_both_beta_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_both_delta_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_both_gamma1_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_both_gamma2_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_both_spk_250ms_bins_50ms_sampled', ...
%     'Binned_data_V4_matchUnits_both_theta_250ms_bins_50ms_sampled', ...
%     ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_alpha_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_beta_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_delta_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_gamma1_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_gamma2_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_spk_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_ambiguous_theta_250ms_bins_50ms_sampled', ...
%     ...
%     'Binned_data_pulvinar_matchUnits_both_alpha_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_both_beta_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_both_delta_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_both_gamma1_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_both_gamma2_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_both_spk_250ms_bins_50ms_sampled', ...
%     'Binned_data_pulvinar_matchUnits_both_theta_250ms_bins_50ms_sampled'};
    'Binned_data_V1_ambiguous_cvsplits14_alpha_250ms_bins_50ms_sampled', ...
    'Binned_data_V1_ambiguous_cvsplits14_beta_250ms_bins_50ms_sampled', ...
    'Binned_data_V1_ambiguous_cvsplits14_delta_250ms_bins_50ms_sampled', ...
    'Binned_data_V1_ambiguous_cvsplits14_gamma1_250ms_bins_50ms_sampled', ...
    'Binned_data_V1_ambiguous_cvsplits14_mua_250ms_bins_50ms_sampled'};

dataSet = 'GFS_Tuebingen'; % 'GFS_NIH'

for flNum = 1:length(flList)

    gfs_create_singleUnitResponsePPT(flList{flNum}, dataSet)

end
